""" Implementations of pre-training losses. """

import torch
from ._base import Loss
from ..base import PretrainingTaskMixin


class TabNetPretrainingLoss(Loss, PretrainingTaskMixin):
    def __init__(self):
        super(TabNetPretrainingLoss, self).__init__()

    def score_func(self, preds, targets, mask, epsilon=1e-9):
        """
        Implementation of self-supervised pre-training loss function.

        Arguments:
            pred (torch.Tensor):
                Reconstruction from tabnet decoder.

            targets (torch.Tensor):
                The emnedded features from embedding encoder.

            mask (torch.Tensor):
                The binary mask generated by binary masker for the reconstruction task.

            epsilon (float):
                A small float value to avoid ZeroDivisionError

        Returns:
            loss (torch.Tensor).
                The pre-training loss.

        """
        errors = preds - targets

